# Generated by Django 4.2.6 on 2023-11-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(choices=[(1, 'One passenger'), (2, 'Two passengers'), (3, 'Three passengers')], default=1),
        ),
    ]
